
version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: next-container
    ports:
      - "8080:3000"
    env_file:
      - .env
    restart: always


