version: "3.9"

services:
  next-app:
    container_name: next-container
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - app-network

  haproxy:
    image: haproxy:latest
    container_name: haproxy-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - next-app
    networks:
      - app-network

networks:
  app-network:
